# Site settings
title: Etrain
description: Tech blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://etrain.xyz"

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

port: 4000
host: localhost


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ["CNAME", "LICENSE", "README.md"]

# multiple language
defaults:
  # default vi
  - values:
      locale: vi
  # config posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
  - scope:
      path: _posts/en/**
      type: posts
    values:
      layout: post
      locale: en
      permalink: /en/posts/:title
  # config pages
  - scope: 
      path: _en/**
    values:
      locale: en

collections:
  en: 
    output: true